#include "loop.h"

static int flags = 0;
const char *usage = "USAGE: gpuloop [-chlo] [-t number of threads]";

__host__ __device__ void short_leaf_loop(int *res, int idx){
    int i;
    int r = 0;

    for(i = 0; i < 1000000; i++){
        r += i;
    }
    res[idx] = r;
}

__host__ __device__ void long_leaf_loop(int *res, int idx){
    int i;
    int r = 0;

    for(i = 0; i < 1000000; i++){
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i++;
        r += i;
    }
    res[idx] = r;
}

__host__ void *short_leaf_host(void *args){
    short_leaf_loop(((ThreadArgs *)args)->res, ((ThreadArgs *)args)->idx);
    free((ThreadArgs *)args);

    return (void *)NULL;
}

__host__ void *long_leaf_host(void *args){
    long_leaf_loop(((ThreadArgs *)args)->res, ((ThreadArgs *)args)->idx);
    free((ThreadArgs *)args);

    return (void *)NULL;
}

__global__ void short_leaf_kernel(int *res, int thread_num){
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if(idx < thread_num){
        short_leaf_loop(res, idx);
    }
}

__global__ void long_leaf_kernel(int *res, int thread_num){
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if(idx < thread_num){
        long_leaf_loop(res, idx);
    }
}

__host__ int *host_loop(int thread_num){
    int *res;
    int idx;
    ThreadArgs *args;
    pthread_t *threads;

    res = (int *)malloc(sizeof(int) * thread_num);
    threads = (pthread_t *)malloc(sizeof(pthread_t) * thread_num);

    stop_watch_start();
    for(idx = 0; idx < thread_num; idx++){
        args = (ThreadArgs *)malloc(sizeof(ThreadArgs));
        args->idx = idx;
        args->res = res;
        if(flags & F_OPT){
            pthread_create(&threads[idx], NULL, long_leaf_host, (void *)args);
        } else{
            pthread_create(&threads[idx], NULL, short_leaf_host, (void *)args);
        }
    }
    for(idx = 0; idx < thread_num; idx++){
        pthread_join(threads[idx], NULL);
    }
    stop_watch_stop();

    free(threads);
    return res;
}

__host__ int *kernel_loop(int thread_num){
    int *res_d, *res;

    cudaMalloc(&res_d, sizeof(int) * thread_num);

    stop_watch_start();
    if(flags & F_OPT){
        long_leaf_kernel<<<thread_num, 1>>>(res_d, thread_num);
    } else{
        short_leaf_kernel<<<thread_num, 1>>>(res_d, thread_num);
    }
    cudaThreadSynchronize();
    stop_watch_stop();

    res = (int *)malloc(sizeof(int) * thread_num);
    cudaMemcpy(res, res_d, sizeof(int) * thread_num, cudaMemcpyDeviceToHost);
    cudaFree(res_d);
    return res;
}

__host__ int main(int argc, char *argv[]){
    extern char *optarg;
    extern int optind, optopt, opterr;
    char c;
    int thread_num = 1;
    int *res;
    int i;

    opterr = 0;
    while((c = getopt(argc, argv, ":chlot:")) != -1){
        switch(c){
            case 'c':
                flags = flags | F_CPU;
                break;
            case 'h':
                puts(usage);
                exit(EXIT_SUCCESS);
            case 'l':
                flags = flags | F_LOG;
                break;
            case 'o':
                flags = flags | F_OPT;
                break;
            case 't':
                thread_num = atoi(optarg);
                break;
            case ':':
                fprintf(stderr, "Option \"%c\" needs argument.\n%s\n", optopt, usage);
                exit(EXIT_FAILURE);
            default:
                fprintf(stderr, "Illigal option \"%c\".\n%s\n", optopt, usage);
                exit(EXIT_FAILURE);
        }
    }

    if(flags & F_CPU){
        res = host_loop(thread_num);
    } else{
        res = kernel_loop(thread_num);
    }

    if(flags & F_LOG){
        printf("%d,%-10.6f\n", thread_num, get_stop_watch_time());
    } else{
        for(i = 0; i < thread_num; i++){
            printf("%d ", res[i]);
        }
        printf("\nExecution time: %10.6f (sec)\n", get_stop_watch_time());
    }
    free(res);

    return EXIT_SUCCESS;
}
